### ISSUE TITLE
Default config is broken due to minepic.org change

### ISSUE THREAD

**Issue by JTHicks26** [ItsNathanG/PictureLogin#2]
minepic.org no longer works with the default `url` entry in the config file.

It should be changed from `https://minepic.org/avatar/8/%uuid%` to `https://minepic.org/avatar/%pname%`.

Or to use a player's UUID instead of PNAME, %uuid% must have the dashes removed before querying `https://minepic.org/avatar/%uuid%`.

**Comment by ItsNathanG** [comment]
Seems to no longer be an issue in the latest version!
